### ISSUE TITLE
Find a solution to Visual Studio DLL

### ISSUE THREAD

**Issue by mattiaisgro** [erebos-project/erebos-api#18]
The DLL compiled for Visual Studio cannot be used without a .def file or manually exporting functions (using __declspec)

**Comment by mattiaisgro** [comment]
* EXPDEF crashes
* gendef doesn't work

**Comment by StefanoBelli** [comment]
~~~
#define ERAPI __declspec(dllexport)
~~~

**Comment by mattiaisgro** [comment]
I added the ERAPI macro but the compiler gives errors about parse_arg function redefinition

**Comment by mattiaisgro** [comment]
**'erebos::parse_arg': redefinition; different linkage**
framework.h:473

**Comment by mattiaisgro** [comment]
The problem is now solved, it had to do with a forward declaration in types.h
