### ISSUE TITLE
Current test approach is bad (see details)

### ISSUE THREAD

**Issue by StefanoBelli** [erebos-project/erebos-api#21]
Current test approach will not work with:
 * Overloaded functions
 * Void returning functions

A solution for the first problem is to make the callback immediatly, with *TEST_START*.

For the second one, maybe a *TEST_START_VOID* macro may be useful

**Comment by mattiaisgro** [comment]
`#define TEST_EXEC_VOID(...) func_ptr(__VA_ARGS__)`

This lets execute a function which returns void, we have to implement TEST_START_VOID
