### ISSUE TITLE
Remove API version defines in favor of CMake

### ISSUE THREAD

**Issue by mattiaisgro** [erebos-project/erebos-api#3]
This code should be enhanced to use CMake:
```
constexpr int API_VERSION_MAJOR = 0;
constexpr int API_VERSION_MINOR = 0;
constexpr int API_VERSION_PATCH = 1;
```

**Comment by StefanoBelli** [comment]
Unique ways we have with CMake are:
 * use an input header configuration file, cmake will replace the pattern with actual values
 * defining macros via add_definitions

**Comment by StefanoBelli** [comment]
You can now define API version via CMake:

Using the project-root CMakeLists.txt, change:
  * API_VERSION_MAJOR
  * API_VERSION_MINOR
  * API_VERSION_PATCH

When configuring (before compile-time), CMake will generate version.h header

**NOTE: version.h IS IN THE GITIGNORE LIST, please don't remove it**
