### ISSUE TITLE
Implement cmd(string) and cmd(string, string*) for command execution

### ISSUE THREAD

**Issue by mattiaisgro** [erebos-project/erebos-api#5]
We should implement two functions for command execution:
* **int cmd(const std::string&)** to execute a command and return the exit code
* **int cmd(const std::string&, std::string&)** to execute a command, write the output to the passed string and return the exit code

**Comment by mattiaisgro** [comment]
_popen does not seem to work on Windows 10

**Comment by StefanoBelli** [comment]
Done
